### ISSUE TITLE
(ERR): bowtie2-align died with signal 13 (PIPE)

### ISSUE THREAD

**Issue by kaeldai** [rachelss/SISRS#12]
Tried running SISRS (develop branch) on a FreeBSD machine, using both minia and velvet. Kept receiving the following error:

> ==== Aligning FILELIST ../SISRS_test_data/T1/T1 ====
> [bam_sort] Use -T PREFIX / -o FILE to specify temporary and final output files
> Usage: samtools sort [options...] [in.bam]
> Options:
>   -l INT     Set compression level, from 0 (uncompressed) to 9 (best)
>   -m INT     Set maximum memory per thread; suffix K/M/G recognized [768M]
>   -n         Sort by read name
>   -o FILE    Write final output to FILE rather than standard output
>   -T PREFIX  Write temporary files to PREFIX.nnnn.bam
>   -@, --threads INT
>              Set number of sorting and compression threads [1]
>       --input-fmt-option OPT[=VAL]
>                Specify a single input file format option in the form
>                of OPTION or OPTION=VALUE
>   -O, --output-fmt FORMAT[,OPT[=VAL]]...
>                Specify output format (SAM, BAM, CRAM)
>       --output-fmt-option OPT[=VAL]
>                Specify a single output file format option in the form
>                of OPTION or OPTION=VALUE
>       --reference FILE
>                Reference sequence FASTA FILE [null]
> (ERR): bowtie2-align died with signal 13 (PIPE) 
> ==== Done Aligning ====

When bowtie finishes the program continues and output for all the bams:

>  [E::hts_open_format] fail to open file '../SISRS_test_data/T1/T1.bam'
> samtools index: failed to open "../SISRS_test_data/T1/T1.bam": No such file or directory

**Comment by kaeldai** [comment]
Ran the command:
> ./sisrs sites -g 1745690 -p 40 -m 4 -f test_data -t .99 -a minia

data was taken from rachelss/SISRS_test_data

**Comment by rachelss** [comment]
The latest version of bowtie2 requires specifying the output file with a flag. I updated the SISRS script and it should work now.
